### ISSUE TITLE
Please support Scalatest 3.2.0

### ISSUE THREAD

**Issue by alexandru** [tkawachi/sbt-doctest#135]
Scalatest 3.2.0 was split into multiple projects, so you can depend just on `FunSuite` for example:

```scala
"org.scalatest"  %%% "scalatest-funsuite"  % ScalaTestVersion % Test,
```

This breaks doctest, because the version check no longer works for sub-modules of `scalatest` and so it detects version `<= 3.0.x`.

**Comment by SethTisue** [comment]
3.2 has a scalatest-core module, so looking for that could be a good way to detect 3.2+

the logic for the check is in `ScalaTestGen.scala`

**Comment by SethTisue** [comment]
regardless of how the check is changed, it might be nice to make the check somehow overridable, via, I don't know, a setting key or a system property or something

happy to test any prospective fix in the context of the Scala community build, where I'm hitting this for a different reason (it's because dbuild rewrites the version numbers of everything)

**Comment by SethTisue** [comment]
thank you! this resolved my problem in the community build

**Comment by alexandru** [comment]
Thanks @tkawachi
